### ISSUE TITLE
Does not work on Zabbix 6.2

### ISSUE THREAD

**Issue by davicavalheiro** [notify-events/zabbix#3]
Apparently this script is no longer compatible with Zabbix 6.2, I found some people with similar problems but no one with a suggestion on how to fix the problem.

Media type test failed.
ReferenceError: identifier 'CurlHttpRequest' undefined
at [anon] (duktape.c:83867) internal
at [anon] (function:1) preventsyield

**Comment by matrozov** [comment]
Thanks for the report. We have analyzed and released a new version of the media-type file that supports Zabbix version 6.
