### ISSUE TITLE
Telegram and Slack notifications fail

### ISSUE THREAD

**Issue by elmanytas** [notify-events/zabbix#4]
Telegram and Slack notifications fail with message "identifier 'CurlHttpRequest' undefined":
```
00:00:00.000 [Debug] [Telegram Webhook] notification failed: ReferenceError: identifier 'CurlHttpRequest' undefined
```

Version: 6.2
Docker image: https://hub.docker.com/layers/zabbix-server-mysql/zabbix/zabbix-server-mysql/6.2-ubuntu-latest/images/sha256-09b3fb375b498460b76f8a313f1e6919b4bcc579a96ee0bf2d31676d59201abf?context=explore

**Comment by matrozov** [comment]
Good afternoon. We have recently added a separate configuration for webhook (media-type) for Zabbix 6.0+. Can you clarify what media-type you used?

**Comment by elmanytas** [comment]
Hi! What recently means? ... docker image is 18 days old.

I used this media-type: https://git.zabbix.com/projects/ZBX/repos/zabbix/browse/templates/media/telegram

**Comment by matrozov** [comment]
This is a repository of the Notify.Events project and its integration with Zabbix. We do not maintain the self-hosted Zabbix and Telegram integration solution you link to. Are you sure you chose the right place for the issue?

**Comment by matrozov** [comment]
> I used this media-type: https://git.zabbix.com/projects/ZBX/repos/zabbix/browse/templates/media/telegram

Are you sure you are using the latest version of this media-type? As I see it, the problem with CurlHttpRequest has already been solved in it. Maybe you just need to update it.

**Comment by elmanytas** [comment]
My fault!! Sorry
